# Generated by Django 2.2.7 on 2019-11-22 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='give_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 23, 44, 10, 319906)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='take_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 23, 44, 10, 319906)),
        ),
    ]
