# Generated by Django 2.2.7 on 2019-11-28 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0005_auto_20191122_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='give_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 11, 43, 39, 35614)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='take_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 11, 43, 39, 35614)),
        ),
    ]
