# Generated by Django 3.1.7 on 2021-05-18 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0007_auto_20191128_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='give_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 0, 25, 44, 438930)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='take_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 0, 25, 44, 438930)),
        ),
    ]
